version: '2'
services:
  yeebulb-api: &yeebulb-api
    build: .
    volumes:
      - .:/usr/yeebulb-api
    environment:
      - FLASK_ENV=development
      - FLASK_APP=src/app.py
      - FLASK_RUN_HOST=0.0.0.0
    ports:
      - 5000:5000
    command: flask run
    depends_on:
      - db

  db:
    image: mongo:4.0-xenial
    command: mongod --smallfiles --quiet
    volumes:
      - .:/mongo/db
    ports:
      - 27017:27017